// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIHealthStatus int32

const (
	APIHealthStatus_UNKNOWN   APIHealthStatus = 0
	APIHealthStatus_HEALTHY   APIHealthStatus = 1
	APIHealthStatus_UNHEALTHY APIHealthStatus = 2
	APIHealthStatus_DEGRADED  APIHealthStatus = 3
)

// Enum value maps for APIHealthStatus.
var (
	APIHealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "DEGRADED",
	}
	APIHealthStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
		"DEGRADED":  3,
	}
)

func (x APIHealthStatus) Enum() *APIHealthStatus {
	p := new(APIHealthStatus)
	*p = x
	return p
}

func (x APIHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (APIHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (APIHealthStatus) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x APIHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use APIHealthStatus.Descriptor instead.
func (APIHealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

// Provider management messages
type APIListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeStatus bool                   `protobuf:"varint,1,opt,name=include_status,json=includeStatus,proto3" json:"include_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIListProvidersRequest) Reset() {
	*x = APIListProvidersRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIListProvidersRequest) ProtoMessage() {}

func (x *APIListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIListProvidersRequest.ProtoReflect.Descriptor instead.
func (*APIListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *APIListProvidersRequest) GetIncludeStatus() bool {
	if x != nil {
		return x.IncludeStatus
	}
	return false
}

type APIListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*APIProviderInfo     `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIListProvidersResponse) Reset() {
	*x = APIListProvidersResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIListProvidersResponse) ProtoMessage() {}

func (x *APIListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIListProvidersResponse.ProtoReflect.Descriptor instead.
func (*APIListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *APIListProvidersResponse) GetProviders() []*APIProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type APIProviderInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SupportedServices []string               `protobuf:"bytes,4,rep,name=supported_services,json=supportedServices,proto3" json:"supported_services,omitempty"`
	Capabilities      map[string]string      `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status            *APIProviderStatus     `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *APIProviderInfo) Reset() {
	*x = APIProviderInfo{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIProviderInfo) ProtoMessage() {}

func (x *APIProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIProviderInfo.ProtoReflect.Descriptor instead.
func (*APIProviderInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *APIProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIProviderInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *APIProviderInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APIProviderInfo) GetSupportedServices() []string {
	if x != nil {
		return x.SupportedServices
	}
	return nil
}

func (x *APIProviderInfo) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *APIProviderInfo) GetStatus() *APIProviderStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type APIProviderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Initialized   bool                   `protobuf:"varint,2,opt,name=initialized,proto3" json:"initialized,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIProviderStatus) Reset() {
	*x = APIProviderStatus{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIProviderStatus) ProtoMessage() {}

func (x *APIProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIProviderStatus.ProtoReflect.Descriptor instead.
func (*APIProviderStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *APIProviderStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *APIProviderStatus) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *APIProviderStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *APIProviderStatus) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

type APIGetProviderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetProviderInfoRequest) Reset() {
	*x = APIGetProviderInfoRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetProviderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetProviderInfoRequest) ProtoMessage() {}

func (x *APIGetProviderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetProviderInfoRequest.ProtoReflect.Descriptor instead.
func (*APIGetProviderInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *APIGetProviderInfoRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type APIProviderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderInfo  *APIProviderInfo       `protobuf:"bytes,1,opt,name=provider_info,json=providerInfo,proto3" json:"provider_info,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIProviderInfoResponse) Reset() {
	*x = APIProviderInfoResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIProviderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIProviderInfoResponse) ProtoMessage() {}

func (x *APIProviderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIProviderInfoResponse.ProtoReflect.Descriptor instead.
func (*APIProviderInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *APIProviderInfoResponse) GetProviderInfo() *APIProviderInfo {
	if x != nil {
		return x.ProviderInfo
	}
	return nil
}

func (x *APIProviderInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Query operation messages
type APIExecuteQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,2,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // "table", "json", "csv"
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIExecuteQueryRequest) Reset() {
	*x = APIExecuteQueryRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIExecuteQueryRequest) ProtoMessage() {}

func (x *APIExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*APIExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *APIExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *APIExecuteQueryRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *APIExecuteQueryRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *APIExecuteQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type APIExecuteQueryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Rows            []*APIQueryResult      `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Columns         []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	RowCount        int32                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *APIExecuteQueryResponse) Reset() {
	*x = APIExecuteQueryResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIExecuteQueryResponse) ProtoMessage() {}

func (x *APIExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*APIExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *APIExecuteQueryResponse) GetRows() []*APIQueryResult {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *APIExecuteQueryResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *APIExecuteQueryResponse) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *APIExecuteQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *APIExecuteQueryResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type APIQueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIQueryResult) Reset() {
	*x = APIQueryResult{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIQueryResult) ProtoMessage() {}

func (x *APIQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIQueryResult.ProtoReflect.Descriptor instead.
func (*APIQueryResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *APIQueryResult) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Health and status messages
type APIHealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIHealthCheckRequest) Reset() {
	*x = APIHealthCheckRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIHealthCheckRequest) ProtoMessage() {}

func (x *APIHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*APIHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

type APIHealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        APIHealthStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=corkscrew.api.APIHealthStatus" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIHealthCheckResponse) Reset() {
	*x = APIHealthCheckResponse{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIHealthCheckResponse) ProtoMessage() {}

func (x *APIHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*APIHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *APIHealthCheckResponse) GetStatus() APIHealthStatus {
	if x != nil {
		return x.Status
	}
	return APIHealthStatus_UNKNOWN
}

func (x *APIHealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *APIHealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *APIHealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type APIGetStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncludeProviders bool                   `protobuf:"varint,1,opt,name=include_providers,json=includeProviders,proto3" json:"include_providers,omitempty"`
	IncludeDatabase  bool                   `protobuf:"varint,2,opt,name=include_database,json=includeDatabase,proto3" json:"include_database,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *APIGetStatusRequest) Reset() {
	*x = APIGetStatusRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetStatusRequest) ProtoMessage() {}

func (x *APIGetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetStatusRequest.ProtoReflect.Descriptor instead.
func (*APIGetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *APIGetStatusRequest) GetIncludeProviders() bool {
	if x != nil {
		return x.IncludeProviders
	}
	return false
}

func (x *APIGetStatusRequest) GetIncludeDatabase() bool {
	if x != nil {
		return x.IncludeDatabase
	}
	return false
}

type APIGetStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OverallStatus  APIHealthStatus        `protobuf:"varint,1,opt,name=overall_status,json=overallStatus,proto3,enum=corkscrew.api.APIHealthStatus" json:"overall_status,omitempty"`
	ProviderStatus []*APIProviderStatus   `protobuf:"bytes,2,rep,name=provider_status,json=providerStatus,proto3" json:"provider_status,omitempty"`
	DatabaseStatus *APIDatabaseStatus     `protobuf:"bytes,3,opt,name=database_status,json=databaseStatus,proto3" json:"database_status,omitempty"`
	SystemStats    *APISystemStats        `protobuf:"bytes,4,opt,name=system_stats,json=systemStats,proto3" json:"system_stats,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *APIGetStatusResponse) Reset() {
	*x = APIGetStatusResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetStatusResponse) ProtoMessage() {}

func (x *APIGetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetStatusResponse.ProtoReflect.Descriptor instead.
func (*APIGetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *APIGetStatusResponse) GetOverallStatus() APIHealthStatus {
	if x != nil {
		return x.OverallStatus
	}
	return APIHealthStatus_UNKNOWN
}

func (x *APIGetStatusResponse) GetProviderStatus() []*APIProviderStatus {
	if x != nil {
		return x.ProviderStatus
	}
	return nil
}

func (x *APIGetStatusResponse) GetDatabaseStatus() *APIDatabaseStatus {
	if x != nil {
		return x.DatabaseStatus
	}
	return nil
}

func (x *APIGetStatusResponse) GetSystemStats() *APISystemStats {
	if x != nil {
		return x.SystemStats
	}
	return nil
}

func (x *APIGetStatusResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type APIDatabaseStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Available      bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	TableCount     int32                  `protobuf:"varint,4,opt,name=table_count,json=tableCount,proto3" json:"table_count,omitempty"`
	TotalResources int64                  `protobuf:"varint,5,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`
	LastScan       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_scan,json=lastScan,proto3" json:"last_scan,omitempty"`
	Error          string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *APIDatabaseStatus) Reset() {
	*x = APIDatabaseStatus{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIDatabaseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDatabaseStatus) ProtoMessage() {}

func (x *APIDatabaseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDatabaseStatus.ProtoReflect.Descriptor instead.
func (*APIDatabaseStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *APIDatabaseStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *APIDatabaseStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APIDatabaseStatus) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *APIDatabaseStatus) GetTableCount() int32 {
	if x != nil {
		return x.TableCount
	}
	return 0
}

func (x *APIDatabaseStatus) GetTotalResources() int64 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *APIDatabaseStatus) GetLastScan() *timestamppb.Timestamp {
	if x != nil {
		return x.LastScan
	}
	return nil
}

func (x *APIDatabaseStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type APISystemStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds     int64                  `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MemoryUsageBytes  int64                  `protobuf:"varint,2,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	TotalRequests     int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors       int64                  `protobuf:"varint,5,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *APISystemStats) Reset() {
	*x = APISystemStats{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISystemStats) ProtoMessage() {}

func (x *APISystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISystemStats.ProtoReflect.Descriptor instead.
func (*APISystemStats) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *APISystemStats) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *APISystemStats) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *APISystemStats) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *APISystemStats) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *APISystemStats) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

// IDMS Discovery messages
type APIDiscoverIDMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForceRefresh  bool                   `protobuf:"varint,1,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIDiscoverIDMSRequest) Reset() {
	*x = APIDiscoverIDMSRequest{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIDiscoverIDMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDiscoverIDMSRequest) ProtoMessage() {}

func (x *APIDiscoverIDMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDiscoverIDMSRequest.ProtoReflect.Descriptor instead.
func (*APIDiscoverIDMSRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *APIDiscoverIDMSRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

type APIDiscoverIDMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Services      []*APIIDMSService      `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	TotalFound    int32                  `protobuf:"varint,3,opt,name=total_found,json=totalFound,proto3" json:"total_found,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Errors        []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	DiscoveredAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIDiscoverIDMSResponse) Reset() {
	*x = APIDiscoverIDMSResponse{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIDiscoverIDMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDiscoverIDMSResponse) ProtoMessage() {}

func (x *APIDiscoverIDMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDiscoverIDMSResponse.ProtoReflect.Descriptor instead.
func (*APIDiscoverIDMSResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *APIDiscoverIDMSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *APIDiscoverIDMSResponse) GetServices() []*APIIDMSService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *APIDiscoverIDMSResponse) GetTotalFound() int32 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

func (x *APIDiscoverIDMSResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *APIDiscoverIDMSResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *APIDiscoverIDMSResponse) GetDiscoveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DiscoveredAt
	}
	return nil
}

func (x *APIDiscoverIDMSResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type APIIDMSService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ServiceType   string                 `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DiscoveredAt  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIIDMSService) Reset() {
	*x = APIIDMSService{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIIDMSService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIIDMSService) ProtoMessage() {}

func (x *APIIDMSService) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIIDMSService.ProtoReflect.Descriptor instead.
func (*APIIDMSService) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *APIIDMSService) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *APIIDMSService) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *APIIDMSService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIIDMSService) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *APIIDMSService) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *APIIDMSService) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *APIIDMSService) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *APIIDMSService) GetDiscoveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DiscoveredAt
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\rcorkscrew.api\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\x17APIListProvidersRequest\x12%\n" +
	"\x0einclude_status\x18\x01 \x01(\bR\rincludeStatus\"X\n" +
	"\x18APIListProvidersResponse\x12<\n" +
	"\tproviders\x18\x01 \x03(\v2\x1e.corkscrew.api.APIProviderInfoR\tproviders\"\xe1\x02\n" +
	"\x0fAPIProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x12supported_services\x18\x04 \x03(\tR\x11supportedServices\x12T\n" +
	"\fcapabilities\x18\x05 \x03(\v20.corkscrew.api.APIProviderInfo.CapabilitiesEntryR\fcapabilities\x128\n" +
	"\x06status\x18\x06 \x01(\v2 .corkscrew.api.APIProviderStatusR\x06status\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x11APIProviderStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12 \n" +
	"\vinitialized\x18\x02 \x01(\bR\vinitialized\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x129\n" +
	"\n" +
	"last_check\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\"7\n" +
	"\x19APIGetProviderInfoRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"t\n" +
	"\x17APIProviderInfoResponse\x12C\n" +
	"\rprovider_info\x18\x01 \x01(\v2\x1e.corkscrew.api.APIProviderInfoR\fproviderInfo\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xff\x01\n" +
	"\x16APIExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12#\n" +
	"\routput_format\x18\x02 \x01(\tR\foutputFormat\x12U\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v25.corkscrew.api.APIExecuteQueryRequest.ParametersEntryR\n" +
	"parameters\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x17APIExecuteQueryResponse\x121\n" +
	"\x04rows\x18\x01 \x03(\v2\x1d.corkscrew.api.APIQueryResultR\x04rows\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x05R\browCount\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\"\x8e\x01\n" +
	"\x0eAPIQueryResult\x12A\n" +
	"\x06values\x18\x01 \x03(\v2).corkscrew.api.APIQueryResult.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15APIHealthCheckRequest\"\xae\x02\n" +
	"\x16APIHealthCheckResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.corkscrew.api.APIHealthStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12L\n" +
	"\adetails\x18\x04 \x03(\v22.corkscrew.api.APIHealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x13APIGetStatusRequest\x12+\n" +
	"\x11include_providers\x18\x01 \x01(\bR\x10includeProviders\x12)\n" +
	"\x10include_database\x18\x02 \x01(\bR\x0fincludeDatabase\"\xef\x02\n" +
	"\x14APIGetStatusResponse\x12E\n" +
	"\x0eoverall_status\x18\x01 \x01(\x0e2\x1e.corkscrew.api.APIHealthStatusR\roverallStatus\x12I\n" +
	"\x0fprovider_status\x18\x02 \x03(\v2 .corkscrew.api.APIProviderStatusR\x0eproviderStatus\x12I\n" +
	"\x0fdatabase_status\x18\x03 \x01(\v2 .corkscrew.api.APIDatabaseStatusR\x0edatabaseStatus\x12@\n" +
	"\fsystem_stats\x18\x04 \x01(\v2\x1d.corkscrew.api.APISystemStatsR\vsystemStats\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xfd\x01\n" +
	"\x11APIDatabaseStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vtable_count\x18\x04 \x01(\x05R\n" +
	"tableCount\x12'\n" +
	"\x0ftotal_resources\x18\x05 \x01(\x03R\x0etotalResources\x127\n" +
	"\tlast_scan\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastScan\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xde\x01\n" +
	"\x0eAPISystemStats\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x03R\ruptimeSeconds\x12,\n" +
	"\x12memory_usage_bytes\x18\x02 \x01(\x03R\x10memoryUsageBytes\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x05 \x01(\x03R\vtotalErrors\"=\n" +
	"\x16APIDiscoverIDMSRequest\x12#\n" +
	"\rforce_refresh\x18\x01 \x01(\bR\fforceRefresh\"\x9f\x02\n" +
	"\x17APIDiscoverIDMSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\bservices\x18\x02 \x03(\v2\x1d.corkscrew.api.APIIDMSServiceR\bservices\x12\x1f\n" +
	"\vtotal_found\x18\x03 \x01(\x05R\n" +
	"totalFound\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\x12?\n" +
	"\rdiscovered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fdiscoveredAt\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xf6\x02\n" +
	"\x0eAPIIDMSService\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12!\n" +
	"\fservice_type\x18\x02 \x01(\tR\vserviceType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12G\n" +
	"\bmetadata\x18\a \x03(\v2+.corkscrew.api.APIIDMSService.MetadataEntryR\bmetadata\x12?\n" +
	"\rdiscovered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fdiscoveredAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*H\n" +
	"\x0fAPIHealthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\f\n" +
	"\bDEGRADED\x10\x032\xcd\x04\n" +
	"\fCorkscrewAPI\x12`\n" +
	"\rListProviders\x12&.corkscrew.api.APIListProvidersRequest\x1a'.corkscrew.api.APIListProvidersResponse\x12c\n" +
	"\x0fGetProviderInfo\x12(.corkscrew.api.APIGetProviderInfoRequest\x1a&.corkscrew.api.APIProviderInfoResponse\x12Z\n" +
	"\vHealthCheck\x12$.corkscrew.api.APIHealthCheckRequest\x1a%.corkscrew.api.APIHealthCheckResponse\x12T\n" +
	"\tGetStatus\x12\".corkscrew.api.APIGetStatusRequest\x1a#.corkscrew.api.APIGetStatusResponse\x12]\n" +
	"\fExecuteQuery\x12%.corkscrew.api.APIExecuteQueryRequest\x1a&.corkscrew.api.APIExecuteQueryResponse\x12e\n" +
	"\x14DiscoverIDMSServices\x12%.corkscrew.api.APIDiscoverIDMSRequest\x1a&.corkscrew.api.APIDiscoverIDMSResponseB,Z*github.com/jlgore/corkscrew/internal/protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_goTypes = []any{
	(APIHealthStatus)(0),              // 0: corkscrew.api.APIHealthStatus
	(*APIListProvidersRequest)(nil),   // 1: corkscrew.api.APIListProvidersRequest
	(*APIListProvidersResponse)(nil),  // 2: corkscrew.api.APIListProvidersResponse
	(*APIProviderInfo)(nil),           // 3: corkscrew.api.APIProviderInfo
	(*APIProviderStatus)(nil),         // 4: corkscrew.api.APIProviderStatus
	(*APIGetProviderInfoRequest)(nil), // 5: corkscrew.api.APIGetProviderInfoRequest
	(*APIProviderInfoResponse)(nil),   // 6: corkscrew.api.APIProviderInfoResponse
	(*APIExecuteQueryRequest)(nil),    // 7: corkscrew.api.APIExecuteQueryRequest
	(*APIExecuteQueryResponse)(nil),   // 8: corkscrew.api.APIExecuteQueryResponse
	(*APIQueryResult)(nil),            // 9: corkscrew.api.APIQueryResult
	(*APIHealthCheckRequest)(nil),     // 10: corkscrew.api.APIHealthCheckRequest
	(*APIHealthCheckResponse)(nil),    // 11: corkscrew.api.APIHealthCheckResponse
	(*APIGetStatusRequest)(nil),       // 12: corkscrew.api.APIGetStatusRequest
	(*APIGetStatusResponse)(nil),      // 13: corkscrew.api.APIGetStatusResponse
	(*APIDatabaseStatus)(nil),         // 14: corkscrew.api.APIDatabaseStatus
	(*APISystemStats)(nil),            // 15: corkscrew.api.APISystemStats
	(*APIDiscoverIDMSRequest)(nil),    // 16: corkscrew.api.APIDiscoverIDMSRequest
	(*APIDiscoverIDMSResponse)(nil),   // 17: corkscrew.api.APIDiscoverIDMSResponse
	(*APIIDMSService)(nil),            // 18: corkscrew.api.APIIDMSService
	nil,                               // 19: corkscrew.api.APIProviderInfo.CapabilitiesEntry
	nil,                               // 20: corkscrew.api.APIExecuteQueryRequest.ParametersEntry
	nil,                               // 21: corkscrew.api.APIQueryResult.ValuesEntry
	nil,                               // 22: corkscrew.api.APIHealthCheckResponse.DetailsEntry
	nil,                               // 23: corkscrew.api.APIIDMSService.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 24: google.protobuf.Timestamp
}
var file_api_proto_depIdxs = []int32{
	3,  // 0: corkscrew.api.APIListProvidersResponse.providers:type_name -> corkscrew.api.APIProviderInfo
	19, // 1: corkscrew.api.APIProviderInfo.capabilities:type_name -> corkscrew.api.APIProviderInfo.CapabilitiesEntry
	4,  // 2: corkscrew.api.APIProviderInfo.status:type_name -> corkscrew.api.APIProviderStatus
	24, // 3: corkscrew.api.APIProviderStatus.last_check:type_name -> google.protobuf.Timestamp
	3,  // 4: corkscrew.api.APIProviderInfoResponse.provider_info:type_name -> corkscrew.api.APIProviderInfo
	20, // 5: corkscrew.api.APIExecuteQueryRequest.parameters:type_name -> corkscrew.api.APIExecuteQueryRequest.ParametersEntry
	9,  // 6: corkscrew.api.APIExecuteQueryResponse.rows:type_name -> corkscrew.api.APIQueryResult
	21, // 7: corkscrew.api.APIQueryResult.values:type_name -> corkscrew.api.APIQueryResult.ValuesEntry
	0,  // 8: corkscrew.api.APIHealthCheckResponse.status:type_name -> corkscrew.api.APIHealthStatus
	24, // 9: corkscrew.api.APIHealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	22, // 10: corkscrew.api.APIHealthCheckResponse.details:type_name -> corkscrew.api.APIHealthCheckResponse.DetailsEntry
	0,  // 11: corkscrew.api.APIGetStatusResponse.overall_status:type_name -> corkscrew.api.APIHealthStatus
	4,  // 12: corkscrew.api.APIGetStatusResponse.provider_status:type_name -> corkscrew.api.APIProviderStatus
	14, // 13: corkscrew.api.APIGetStatusResponse.database_status:type_name -> corkscrew.api.APIDatabaseStatus
	15, // 14: corkscrew.api.APIGetStatusResponse.system_stats:type_name -> corkscrew.api.APISystemStats
	24, // 15: corkscrew.api.APIGetStatusResponse.timestamp:type_name -> google.protobuf.Timestamp
	24, // 16: corkscrew.api.APIDatabaseStatus.last_scan:type_name -> google.protobuf.Timestamp
	18, // 17: corkscrew.api.APIDiscoverIDMSResponse.services:type_name -> corkscrew.api.APIIDMSService
	24, // 18: corkscrew.api.APIDiscoverIDMSResponse.discovered_at:type_name -> google.protobuf.Timestamp
	23, // 19: corkscrew.api.APIIDMSService.metadata:type_name -> corkscrew.api.APIIDMSService.MetadataEntry
	24, // 20: corkscrew.api.APIIDMSService.discovered_at:type_name -> google.protobuf.Timestamp
	1,  // 21: corkscrew.api.CorkscrewAPI.ListProviders:input_type -> corkscrew.api.APIListProvidersRequest
	5,  // 22: corkscrew.api.CorkscrewAPI.GetProviderInfo:input_type -> corkscrew.api.APIGetProviderInfoRequest
	10, // 23: corkscrew.api.CorkscrewAPI.HealthCheck:input_type -> corkscrew.api.APIHealthCheckRequest
	12, // 24: corkscrew.api.CorkscrewAPI.GetStatus:input_type -> corkscrew.api.APIGetStatusRequest
	7,  // 25: corkscrew.api.CorkscrewAPI.ExecuteQuery:input_type -> corkscrew.api.APIExecuteQueryRequest
	16, // 26: corkscrew.api.CorkscrewAPI.DiscoverIDMSServices:input_type -> corkscrew.api.APIDiscoverIDMSRequest
	2,  // 27: corkscrew.api.CorkscrewAPI.ListProviders:output_type -> corkscrew.api.APIListProvidersResponse
	6,  // 28: corkscrew.api.CorkscrewAPI.GetProviderInfo:output_type -> corkscrew.api.APIProviderInfoResponse
	11, // 29: corkscrew.api.CorkscrewAPI.HealthCheck:output_type -> corkscrew.api.APIHealthCheckResponse
	13, // 30: corkscrew.api.CorkscrewAPI.GetStatus:output_type -> corkscrew.api.APIGetStatusResponse
	8,  // 31: corkscrew.api.CorkscrewAPI.ExecuteQuery:output_type -> corkscrew.api.APIExecuteQueryResponse
	17, // 32: corkscrew.api.CorkscrewAPI.DiscoverIDMSServices:output_type -> corkscrew.api.APIDiscoverIDMSResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
