// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CorkscrewAPI_ListProviders_FullMethodName        = "/corkscrew.api.CorkscrewAPI/ListProviders"
	CorkscrewAPI_GetProviderInfo_FullMethodName      = "/corkscrew.api.CorkscrewAPI/GetProviderInfo"
	CorkscrewAPI_HealthCheck_FullMethodName          = "/corkscrew.api.CorkscrewAPI/HealthCheck"
	CorkscrewAPI_GetStatus_FullMethodName            = "/corkscrew.api.CorkscrewAPI/GetStatus"
	CorkscrewAPI_ExecuteQuery_FullMethodName         = "/corkscrew.api.CorkscrewAPI/ExecuteQuery"
	CorkscrewAPI_DiscoverIDMSServices_FullMethodName = "/corkscrew.api.CorkscrewAPI/DiscoverIDMSServices"
)

// CorkscrewAPIClient is the client API for CorkscrewAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The main Corkscrew API service
type CorkscrewAPIClient interface {
	// Provider management
	ListProviders(ctx context.Context, in *APIListProvidersRequest, opts ...grpc.CallOption) (*APIListProvidersResponse, error)
	GetProviderInfo(ctx context.Context, in *APIGetProviderInfoRequest, opts ...grpc.CallOption) (*APIProviderInfoResponse, error)
	// Health and status
	HealthCheck(ctx context.Context, in *APIHealthCheckRequest, opts ...grpc.CallOption) (*APIHealthCheckResponse, error)
	GetStatus(ctx context.Context, in *APIGetStatusRequest, opts ...grpc.CallOption) (*APIGetStatusResponse, error)
	// Query operations
	ExecuteQuery(ctx context.Context, in *APIExecuteQueryRequest, opts ...grpc.CallOption) (*APIExecuteQueryResponse, error)
	// IDMS Discovery
	DiscoverIDMSServices(ctx context.Context, in *APIDiscoverIDMSRequest, opts ...grpc.CallOption) (*APIDiscoverIDMSResponse, error)
}

type corkscrewAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCorkscrewAPIClient(cc grpc.ClientConnInterface) CorkscrewAPIClient {
	return &corkscrewAPIClient{cc}
}

func (c *corkscrewAPIClient) ListProviders(ctx context.Context, in *APIListProvidersRequest, opts ...grpc.CallOption) (*APIListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIListProvidersResponse)
	err := c.cc.Invoke(ctx, CorkscrewAPI_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkscrewAPIClient) GetProviderInfo(ctx context.Context, in *APIGetProviderInfoRequest, opts ...grpc.CallOption) (*APIProviderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIProviderInfoResponse)
	err := c.cc.Invoke(ctx, CorkscrewAPI_GetProviderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkscrewAPIClient) HealthCheck(ctx context.Context, in *APIHealthCheckRequest, opts ...grpc.CallOption) (*APIHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIHealthCheckResponse)
	err := c.cc.Invoke(ctx, CorkscrewAPI_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkscrewAPIClient) GetStatus(ctx context.Context, in *APIGetStatusRequest, opts ...grpc.CallOption) (*APIGetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIGetStatusResponse)
	err := c.cc.Invoke(ctx, CorkscrewAPI_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkscrewAPIClient) ExecuteQuery(ctx context.Context, in *APIExecuteQueryRequest, opts ...grpc.CallOption) (*APIExecuteQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIExecuteQueryResponse)
	err := c.cc.Invoke(ctx, CorkscrewAPI_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *corkscrewAPIClient) DiscoverIDMSServices(ctx context.Context, in *APIDiscoverIDMSRequest, opts ...grpc.CallOption) (*APIDiscoverIDMSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIDiscoverIDMSResponse)
	err := c.cc.Invoke(ctx, CorkscrewAPI_DiscoverIDMSServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CorkscrewAPIServer is the server API for CorkscrewAPI service.
// All implementations must embed UnimplementedCorkscrewAPIServer
// for forward compatibility.
//
// The main Corkscrew API service
type CorkscrewAPIServer interface {
	// Provider management
	ListProviders(context.Context, *APIListProvidersRequest) (*APIListProvidersResponse, error)
	GetProviderInfo(context.Context, *APIGetProviderInfoRequest) (*APIProviderInfoResponse, error)
	// Health and status
	HealthCheck(context.Context, *APIHealthCheckRequest) (*APIHealthCheckResponse, error)
	GetStatus(context.Context, *APIGetStatusRequest) (*APIGetStatusResponse, error)
	// Query operations
	ExecuteQuery(context.Context, *APIExecuteQueryRequest) (*APIExecuteQueryResponse, error)
	// IDMS Discovery
	DiscoverIDMSServices(context.Context, *APIDiscoverIDMSRequest) (*APIDiscoverIDMSResponse, error)
	mustEmbedUnimplementedCorkscrewAPIServer()
}

// UnimplementedCorkscrewAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCorkscrewAPIServer struct{}

func (UnimplementedCorkscrewAPIServer) ListProviders(context.Context, *APIListProvidersRequest) (*APIListProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedCorkscrewAPIServer) GetProviderInfo(context.Context, *APIGetProviderInfoRequest) (*APIProviderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderInfo not implemented")
}
func (UnimplementedCorkscrewAPIServer) HealthCheck(context.Context, *APIHealthCheckRequest) (*APIHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCorkscrewAPIServer) GetStatus(context.Context, *APIGetStatusRequest) (*APIGetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCorkscrewAPIServer) ExecuteQuery(context.Context, *APIExecuteQueryRequest) (*APIExecuteQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedCorkscrewAPIServer) DiscoverIDMSServices(context.Context, *APIDiscoverIDMSRequest) (*APIDiscoverIDMSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverIDMSServices not implemented")
}
func (UnimplementedCorkscrewAPIServer) mustEmbedUnimplementedCorkscrewAPIServer() {}
func (UnimplementedCorkscrewAPIServer) testEmbeddedByValue()                      {}

// UnsafeCorkscrewAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CorkscrewAPIServer will
// result in compilation errors.
type UnsafeCorkscrewAPIServer interface {
	mustEmbedUnimplementedCorkscrewAPIServer()
}

func RegisterCorkscrewAPIServer(s grpc.ServiceRegistrar, srv CorkscrewAPIServer) {
	// If the following call pancis, it indicates UnimplementedCorkscrewAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CorkscrewAPI_ServiceDesc, srv)
}

func _CorkscrewAPI_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkscrewAPIServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkscrewAPI_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkscrewAPIServer).ListProviders(ctx, req.(*APIListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkscrewAPI_GetProviderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIGetProviderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkscrewAPIServer).GetProviderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkscrewAPI_GetProviderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkscrewAPIServer).GetProviderInfo(ctx, req.(*APIGetProviderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkscrewAPI_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkscrewAPIServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkscrewAPI_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkscrewAPIServer).HealthCheck(ctx, req.(*APIHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkscrewAPI_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIGetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkscrewAPIServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkscrewAPI_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkscrewAPIServer).GetStatus(ctx, req.(*APIGetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkscrewAPI_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkscrewAPIServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkscrewAPI_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkscrewAPIServer).ExecuteQuery(ctx, req.(*APIExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CorkscrewAPI_DiscoverIDMSServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIDiscoverIDMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorkscrewAPIServer).DiscoverIDMSServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CorkscrewAPI_DiscoverIDMSServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorkscrewAPIServer).DiscoverIDMSServices(ctx, req.(*APIDiscoverIDMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CorkscrewAPI_ServiceDesc is the grpc.ServiceDesc for CorkscrewAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CorkscrewAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corkscrew.api.CorkscrewAPI",
	HandlerType: (*CorkscrewAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProviders",
			Handler:    _CorkscrewAPI_ListProviders_Handler,
		},
		{
			MethodName: "GetProviderInfo",
			Handler:    _CorkscrewAPI_GetProviderInfo_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CorkscrewAPI_HealthCheck_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _CorkscrewAPI_GetStatus_Handler,
		},
		{
			MethodName: "ExecuteQuery",
			Handler:    _CorkscrewAPI_ExecuteQuery_Handler,
		},
		{
			MethodName: "DiscoverIDMSServices",
			Handler:    _CorkscrewAPI_DiscoverIDMSServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
