// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: scanner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{0}
}

// Plugin lifecycle messages
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CacheDir      string                 `protobuf:"bytes,3,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *InitializeRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitializeRequest) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InitializeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InitializeResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProviderInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedServices []string               `protobuf:"bytes,3,rep,name=supported_services,json=supportedServices,proto3" json:"supported_services,omitempty"`
	Capabilities      map[string]string      `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProviderInfoResponse) Reset() {
	*x = ProviderInfoResponse{}
	mi := &file_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfoResponse) ProtoMessage() {}

func (x *ProviderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfoResponse.ProtoReflect.Descriptor instead.
func (*ProviderInfoResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderInfoResponse) GetSupportedServices() []string {
	if x != nil {
		return x.SupportedServices
	}
	return nil
}

func (x *ProviderInfoResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Service discovery messages
type DiscoverServicesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ForceRefresh    bool                   `protobuf:"varint,1,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	IncludeServices []string               `protobuf:"bytes,2,rep,name=include_services,json=includeServices,proto3" json:"include_services,omitempty"`
	ExcludeServices []string               `protobuf:"bytes,3,rep,name=exclude_services,json=excludeServices,proto3" json:"exclude_services,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiscoverServicesRequest) Reset() {
	*x = DiscoverServicesRequest{}
	mi := &file_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverServicesRequest) ProtoMessage() {}

func (x *DiscoverServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverServicesRequest.ProtoReflect.Descriptor instead.
func (*DiscoverServicesRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverServicesRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *DiscoverServicesRequest) GetIncludeServices() []string {
	if x != nil {
		return x.IncludeServices
	}
	return nil
}

func (x *DiscoverServicesRequest) GetExcludeServices() []string {
	if x != nil {
		return x.ExcludeServices
	}
	return nil
}

type DiscoverServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	DiscoveredAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,3,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverServicesResponse) Reset() {
	*x = DiscoverServicesResponse{}
	mi := &file_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverServicesResponse) ProtoMessage() {}

func (x *DiscoverServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverServicesResponse.ProtoReflect.Descriptor instead.
func (*DiscoverServicesResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoverServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DiscoverServicesResponse) GetDiscoveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DiscoveredAt
	}
	return nil
}

func (x *DiscoverServicesResponse) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

type ServiceInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName         string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PackageName         string                 `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	ClientType          string                 `protobuf:"bytes,4,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	ResourceTypes       []*ResourceType        `protobuf:"bytes,5,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,6,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServiceInfo) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ServiceInfo) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *ServiceInfo) GetResourceTypes() []*ResourceType {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *ServiceInfo) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

type ResourceType struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Name              string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeName          string                  `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	ListOperation     string                  `protobuf:"bytes,3,opt,name=list_operation,json=listOperation,proto3" json:"list_operation,omitempty"`
	DescribeOperation string                  `protobuf:"bytes,4,opt,name=describe_operation,json=describeOperation,proto3" json:"describe_operation,omitempty"`
	GetOperation      string                  `protobuf:"bytes,5,opt,name=get_operation,json=getOperation,proto3" json:"get_operation,omitempty"`
	IdField           string                  `protobuf:"bytes,6,opt,name=id_field,json=idField,proto3" json:"id_field,omitempty"`
	NameField         string                  `protobuf:"bytes,7,opt,name=name_field,json=nameField,proto3" json:"name_field,omitempty"`
	ArnField          string                  `protobuf:"bytes,8,opt,name=arn_field,json=arnField,proto3" json:"arn_field,omitempty"`
	SupportsTags      bool                    `protobuf:"varint,9,opt,name=supports_tags,json=supportsTags,proto3" json:"supports_tags,omitempty"`
	Paginated         bool                    `protobuf:"varint,10,opt,name=paginated,proto3" json:"paginated,omitempty"`
	Relationships     []*ResourceRelationship `protobuf:"bytes,11,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceType) Reset() {
	*x = ResourceType{}
	mi := &file_scanner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceType) ProtoMessage() {}

func (x *ResourceType) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceType.ProtoReflect.Descriptor instead.
func (*ResourceType) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ResourceType) GetListOperation() string {
	if x != nil {
		return x.ListOperation
	}
	return ""
}

func (x *ResourceType) GetDescribeOperation() string {
	if x != nil {
		return x.DescribeOperation
	}
	return ""
}

func (x *ResourceType) GetGetOperation() string {
	if x != nil {
		return x.GetOperation
	}
	return ""
}

func (x *ResourceType) GetIdField() string {
	if x != nil {
		return x.IdField
	}
	return ""
}

func (x *ResourceType) GetNameField() string {
	if x != nil {
		return x.NameField
	}
	return ""
}

func (x *ResourceType) GetArnField() string {
	if x != nil {
		return x.ArnField
	}
	return ""
}

func (x *ResourceType) GetSupportsTags() bool {
	if x != nil {
		return x.SupportsTags
	}
	return false
}

func (x *ResourceType) GetPaginated() bool {
	if x != nil {
		return x.Paginated
	}
	return false
}

func (x *ResourceType) GetRelationships() []*ResourceRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

type ResourceRelationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetType       string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	RelationshipType string                 `protobuf:"bytes,2,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	FieldName        string                 `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	IsArray          bool                   `protobuf:"varint,4,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceRelationship) Reset() {
	*x = ResourceRelationship{}
	mi := &file_scanner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRelationship) ProtoMessage() {}

func (x *ResourceRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRelationship.ProtoReflect.Descriptor instead.
func (*ResourceRelationship) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceRelationship) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ResourceRelationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *ResourceRelationship) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *ResourceRelationship) GetIsArray() bool {
	if x != nil {
		return x.IsArray
	}
	return false
}

// Scanner generation messages
type GenerateScannersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Services        []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	GenerateAll     bool                   `protobuf:"varint,2,opt,name=generate_all,json=generateAll,proto3" json:"generate_all,omitempty"`
	ForceRegenerate bool                   `protobuf:"varint,3,opt,name=force_regenerate,json=forceRegenerate,proto3" json:"force_regenerate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateScannersRequest) Reset() {
	*x = GenerateScannersRequest{}
	mi := &file_scanner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScannersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScannersRequest) ProtoMessage() {}

func (x *GenerateScannersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScannersRequest.ProtoReflect.Descriptor instead.
func (*GenerateScannersRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateScannersRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GenerateScannersRequest) GetGenerateAll() bool {
	if x != nil {
		return x.GenerateAll
	}
	return false
}

func (x *GenerateScannersRequest) GetForceRegenerate() bool {
	if x != nil {
		return x.ForceRegenerate
	}
	return false
}

type GenerateScannersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scanners       []*GeneratedScanner    `protobuf:"bytes,1,rep,name=scanners,proto3" json:"scanners,omitempty"`
	Errors         []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	GeneratedCount int32                  `protobuf:"varint,3,opt,name=generated_count,json=generatedCount,proto3" json:"generated_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateScannersResponse) Reset() {
	*x = GenerateScannersResponse{}
	mi := &file_scanner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScannersResponse) ProtoMessage() {}

func (x *GenerateScannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScannersResponse.ProtoReflect.Descriptor instead.
func (*GenerateScannersResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateScannersResponse) GetScanners() []*GeneratedScanner {
	if x != nil {
		return x.Scanners
	}
	return nil
}

func (x *GenerateScannersResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GenerateScannersResponse) GetGeneratedCount() int32 {
	if x != nil {
		return x.GeneratedCount
	}
	return 0
}

type GeneratedScanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ResourceTypes []string               `protobuf:"bytes,3,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedScanner) Reset() {
	*x = GeneratedScanner{}
	mi := &file_scanner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedScanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedScanner) ProtoMessage() {}

func (x *GeneratedScanner) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedScanner.ProtoReflect.Descriptor instead.
func (*GeneratedScanner) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{11}
}

func (x *GeneratedScanner) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GeneratedScanner) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GeneratedScanner) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *GeneratedScanner) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

// Resource operation messages
type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NextToken     string                 `protobuf:"bytes,5,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	MaxResults    int32                  `protobuf:"varint,6,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_scanner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{12}
}

func (x *ListResourcesRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ListResourcesRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListResourcesRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListResourcesRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListResourcesRequest) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *ListResourcesRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ResourceRef         `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_scanner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{13}
}

func (x *ListResourcesResponse) GetResources() []*ResourceRef {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourcesResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *ListResourcesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListResourcesResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ResourceRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Service         string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Region          string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	BasicAttributes map[string]string      `protobuf:"bytes,6,rep,name=basic_attributes,json=basicAttributes,proto3" json:"basic_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_scanner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{14}
}

func (x *ResourceRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceRef) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResourceRef) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ResourceRef) GetBasicAttributes() map[string]string {
	if x != nil {
		return x.BasicAttributes
	}
	return nil
}

type DescribeResourceRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ResourceRef          *ResourceRef           `protobuf:"bytes,1,opt,name=resource_ref,json=resourceRef,proto3" json:"resource_ref,omitempty"`
	IncludeRelationships bool                   `protobuf:"varint,2,opt,name=include_relationships,json=includeRelationships,proto3" json:"include_relationships,omitempty"`
	IncludeTags          bool                   `protobuf:"varint,3,opt,name=include_tags,json=includeTags,proto3" json:"include_tags,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DescribeResourceRequest) Reset() {
	*x = DescribeResourceRequest{}
	mi := &file_scanner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResourceRequest) ProtoMessage() {}

func (x *DescribeResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResourceRequest.ProtoReflect.Descriptor instead.
func (*DescribeResourceRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{15}
}

func (x *DescribeResourceRequest) GetResourceRef() *ResourceRef {
	if x != nil {
		return x.ResourceRef
	}
	return nil
}

func (x *DescribeResourceRequest) GetIncludeRelationships() bool {
	if x != nil {
		return x.IncludeRelationships
	}
	return false
}

func (x *DescribeResourceRequest) GetIncludeTags() bool {
	if x != nil {
		return x.IncludeTags
	}
	return false
}

type DescribeResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResourceResponse) Reset() {
	*x = DescribeResourceResponse{}
	mi := &file_scanner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResourceResponse) ProtoMessage() {}

func (x *DescribeResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResourceResponse.ProtoReflect.Descriptor instead.
func (*DescribeResourceResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{16}
}

func (x *DescribeResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DescribeResourceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Universal resource model
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Core identification
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Service  string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Id       string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Location and hierarchy
	Region    string `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	AccountId string `protobuf:"bytes,7,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ParentId  string `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Arn       string `protobuf:"bytes,9,opt,name=arn,proto3" json:"arn,omitempty"`
	// Metadata
	Tags         map[string]string      `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	DiscoveredAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	// Relationships and raw data
	Relationships []*Relationship `protobuf:"bytes,14,rep,name=relationships,proto3" json:"relationships,omitempty"`
	RawData       string          `protobuf:"bytes,15,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	Attributes    string          `protobuf:"bytes,16,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_scanner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{17}
}

func (x *Resource) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Resource) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Resource) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Resource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Resource) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

func (x *Resource) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Resource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resource) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *Resource) GetDiscoveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DiscoveredAt
	}
	return nil
}

func (x *Resource) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *Resource) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *Resource) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

type Relationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetId         string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType       string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetService    string                 `protobuf:"bytes,3,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	RelationshipType string                 `protobuf:"bytes,4,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	Properties       map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_scanner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{18}
}

func (x *Relationship) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Relationship) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *Relationship) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *Relationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *Relationship) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Schema messages
type GetSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // "sql", "json", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemasRequest) Reset() {
	*x = GetSchemasRequest{}
	mi := &file_scanner_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemasRequest) ProtoMessage() {}

func (x *GetSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemasRequest.ProtoReflect.Descriptor instead.
func (*GetSchemasRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{19}
}

func (x *GetSchemasRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GetSchemasRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type SchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*Schema              `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaResponse) Reset() {
	*x = SchemaResponse{}
	mi := &file_scanner_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaResponse) ProtoMessage() {}

func (x *SchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaResponse.ProtoReflect.Descriptor instead.
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{20}
}

func (x *SchemaResponse) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Sql           string                 `protobuf:"bytes,4,opt,name=sql,proto3" json:"sql,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_scanner_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{21}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Schema) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Schema) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *Schema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Schema) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Batch scanning messages
type BatchScanRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Services             []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	ResourceTypes        []string               `protobuf:"bytes,2,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	Region               string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Filters              map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IncludeRelationships bool                   `protobuf:"varint,5,opt,name=include_relationships,json=includeRelationships,proto3" json:"include_relationships,omitempty"`
	Concurrency          int32                  `protobuf:"varint,6,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BatchScanRequest) Reset() {
	*x = BatchScanRequest{}
	mi := &file_scanner_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScanRequest) ProtoMessage() {}

func (x *BatchScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScanRequest.ProtoReflect.Descriptor instead.
func (*BatchScanRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{22}
}

func (x *BatchScanRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *BatchScanRequest) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *BatchScanRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *BatchScanRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *BatchScanRequest) GetIncludeRelationships() bool {
	if x != nil {
		return x.IncludeRelationships
	}
	return false
}

func (x *BatchScanRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type BatchScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Stats         *ScanStats             `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScanResponse) Reset() {
	*x = BatchScanResponse{}
	mi := &file_scanner_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScanResponse) ProtoMessage() {}

func (x *BatchScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScanResponse.ProtoReflect.Descriptor instead.
func (*BatchScanResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{23}
}

func (x *BatchScanResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *BatchScanResponse) GetStats() *ScanStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *BatchScanResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type StreamScanRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Services             []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	ResourceTypes        []string               `protobuf:"bytes,2,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	Region               string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Filters              map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IncludeRelationships bool                   `protobuf:"varint,5,opt,name=include_relationships,json=includeRelationships,proto3" json:"include_relationships,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StreamScanRequest) Reset() {
	*x = StreamScanRequest{}
	mi := &file_scanner_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamScanRequest) ProtoMessage() {}

func (x *StreamScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamScanRequest.ProtoReflect.Descriptor instead.
func (*StreamScanRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{24}
}

func (x *StreamScanRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *StreamScanRequest) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *StreamScanRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *StreamScanRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *StreamScanRequest) GetIncludeRelationships() bool {
	if x != nil {
		return x.IncludeRelationships
	}
	return false
}

type ScanStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalResources  int32                  `protobuf:"varint,1,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`
	FailedResources int32                  `protobuf:"varint,2,opt,name=failed_resources,json=failedResources,proto3" json:"failed_resources,omitempty"`
	DurationMs      int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ResourceCounts  map[string]int32       `protobuf:"bytes,4,rep,name=resource_counts,json=resourceCounts,proto3" json:"resource_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ServiceCounts   map[string]int32       `protobuf:"bytes,5,rep,name=service_counts,json=serviceCounts,proto3" json:"service_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScanStats) Reset() {
	*x = ScanStats{}
	mi := &file_scanner_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanStats) ProtoMessage() {}

func (x *ScanStats) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanStats.ProtoReflect.Descriptor instead.
func (*ScanStats) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{25}
}

func (x *ScanStats) GetTotalResources() int32 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *ScanStats) GetFailedResources() int32 {
	if x != nil {
		return x.FailedResources
	}
	return 0
}

func (x *ScanStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ScanStats) GetResourceCounts() map[string]int32 {
	if x != nil {
		return x.ResourceCounts
	}
	return nil
}

func (x *ScanStats) GetServiceCounts() map[string]int32 {
	if x != nil {
		return x.ServiceCounts
	}
	return nil
}

// Legacy messages for backward compatibility
type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceTypes []string               `protobuf:"bytes,3,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	NextToken     string                 `protobuf:"bytes,4,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	MaxResults    int32                  `protobuf:"varint,5,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_scanner_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{26}
}

func (x *ScanRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ScanRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ScanRequest) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *ScanRequest) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *ScanRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stats         *ScanStats             `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_scanner_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{27}
}

func (x *ScanResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ScanResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *ScanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScanResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ScanResponse) GetStats() *ScanStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ServiceInfoResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceName         string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version             string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedResources  []string               `protobuf:"bytes,3,rep,name=supported_resources,json=supportedResources,proto3" json:"supported_resources,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,4,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	Capabilities        map[string]string      `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceInfoResponse) Reset() {
	*x = ServiceInfoResponse{}
	mi := &file_scanner_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoResponse) ProtoMessage() {}

func (x *ServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*ServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{28}
}

func (x *ServiceInfoResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfoResponse) GetSupportedResources() []string {
	if x != nil {
		return x.SupportedResources
	}
	return nil
}

func (x *ServiceInfoResponse) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

func (x *ServiceInfoResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_scanner_proto protoreflect.FileDescriptor

const file_scanner_proto_rawDesc = "" +
	"\n" +
	"\rscanner.proto\x12\tcorkscrew\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xc9\x01\n" +
	"\x11InitializeRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12@\n" +
	"\x06config\x18\x02 \x03(\v2(.corkscrew.InitializeRequest.ConfigEntryR\x06config\x12\x1b\n" +
	"\tcache_dir\x18\x03 \x01(\tR\bcacheDir\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\x12InitializeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.corkscrew.InitializeResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x02\n" +
	"\x14ProviderInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12-\n" +
	"\x12supported_services\x18\x03 \x03(\tR\x11supportedServices\x12U\n" +
	"\fcapabilities\x18\x04 \x03(\v21.corkscrew.ProviderInfoResponse.CapabilitiesEntryR\fcapabilities\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\x17DiscoverServicesRequest\x12#\n" +
	"\rforce_refresh\x18\x01 \x01(\bR\fforceRefresh\x12)\n" +
	"\x10include_services\x18\x02 \x03(\tR\x0fincludeServices\x12)\n" +
	"\x10exclude_services\x18\x03 \x03(\tR\x0fexcludeServices\"\xb0\x01\n" +
	"\x18DiscoverServicesResponse\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.corkscrew.ServiceInfoR\bservices\x12?\n" +
	"\rdiscovered_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fdiscoveredAt\x12\x1f\n" +
	"\vsdk_version\x18\x03 \x01(\tR\n" +
	"sdkVersion\"\xfb\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12\x1f\n" +
	"\vclient_type\x18\x04 \x01(\tR\n" +
	"clientType\x12>\n" +
	"\x0eresource_types\x18\x05 \x03(\v2\x17.corkscrew.ResourceTypeR\rresourceTypes\x121\n" +
	"\x14required_permissions\x18\x06 \x03(\tR\x13requiredPermissions\"\x9b\x03\n" +
	"\fResourceType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12%\n" +
	"\x0elist_operation\x18\x03 \x01(\tR\rlistOperation\x12-\n" +
	"\x12describe_operation\x18\x04 \x01(\tR\x11describeOperation\x12#\n" +
	"\rget_operation\x18\x05 \x01(\tR\fgetOperation\x12\x19\n" +
	"\bid_field\x18\x06 \x01(\tR\aidField\x12\x1d\n" +
	"\n" +
	"name_field\x18\a \x01(\tR\tnameField\x12\x1b\n" +
	"\tarn_field\x18\b \x01(\tR\barnField\x12#\n" +
	"\rsupports_tags\x18\t \x01(\bR\fsupportsTags\x12\x1c\n" +
	"\tpaginated\x18\n" +
	" \x01(\bR\tpaginated\x12E\n" +
	"\rrelationships\x18\v \x03(\v2\x1f.corkscrew.ResourceRelationshipR\rrelationships\"\x9e\x01\n" +
	"\x14ResourceRelationship\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12+\n" +
	"\x11relationship_type\x18\x02 \x01(\tR\x10relationshipType\x12\x1d\n" +
	"\n" +
	"field_name\x18\x03 \x01(\tR\tfieldName\x12\x19\n" +
	"\bis_array\x18\x04 \x01(\bR\aisArray\"\x83\x01\n" +
	"\x17GenerateScannersRequest\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12!\n" +
	"\fgenerate_all\x18\x02 \x01(\bR\vgenerateAll\x12)\n" +
	"\x10force_regenerate\x18\x03 \x01(\bR\x0fforceRegenerate\"\x94\x01\n" +
	"\x18GenerateScannersResponse\x127\n" +
	"\bscanners\x18\x01 \x03(\v2\x1b.corkscrew.GeneratedScannerR\bscanners\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12'\n" +
	"\x0fgenerated_count\x18\x03 \x01(\x05R\x0egeneratedCount\"\xaf\x01\n" +
	"\x10GeneratedScanner\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12%\n" +
	"\x0eresource_types\x18\x03 \x03(\tR\rresourceTypes\x12=\n" +
	"\fgenerated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\xb1\x02\n" +
	"\x14ListResourcesRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12F\n" +
	"\afilters\x18\x04 \x03(\v2,.corkscrew.ListResourcesRequest.FiltersEntryR\afilters\x12\x1d\n" +
	"\n" +
	"next_token\x18\x05 \x01(\tR\tnextToken\x12\x1f\n" +
	"\vmax_results\x18\x06 \x01(\x05R\n" +
	"maxResults\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x02\n" +
	"\x15ListResourcesResponse\x124\n" +
	"\tresources\x18\x01 \x03(\v2\x16.corkscrew.ResourceRefR\tresources\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..corkscrew.ListResourcesResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\vResourceRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12V\n" +
	"\x10basic_attributes\x18\x06 \x03(\v2+.corkscrew.ResourceRef.BasicAttributesEntryR\x0fbasicAttributes\x1aB\n" +
	"\x14BasicAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x17DescribeResourceRequest\x129\n" +
	"\fresource_ref\x18\x01 \x01(\v2\x16.corkscrew.ResourceRefR\vresourceRef\x123\n" +
	"\x15include_relationships\x18\x02 \x01(\bR\x14includeRelationships\x12!\n" +
	"\finclude_tags\x18\x03 \x01(\bR\vincludeTags\"a\n" +
	"\x18DescribeResourceResponse\x12/\n" +
	"\bresource\x18\x01 \x01(\v2\x13.corkscrew.ResourceR\bresource\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xfd\x04\n" +
	"\bResource\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"account_id\x18\a \x01(\tR\taccountId\x12\x1b\n" +
	"\tparent_id\x18\b \x01(\tR\bparentId\x12\x10\n" +
	"\x03arn\x18\t \x01(\tR\x03arn\x121\n" +
	"\x04tags\x18\n" +
	" \x03(\v2\x1d.corkscrew.Resource.TagsEntryR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12?\n" +
	"\rdiscovered_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\fdiscoveredAt\x12=\n" +
	"\rrelationships\x18\x0e \x03(\v2\x17.corkscrew.RelationshipR\rrelationships\x12\x19\n" +
	"\braw_data\x18\x0f \x01(\tR\arawData\x12\x1e\n" +
	"\n" +
	"attributes\x18\x10 \x01(\tR\n" +
	"attributes\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x02\n" +
	"\fRelationship\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12%\n" +
	"\x0etarget_service\x18\x03 \x01(\tR\rtargetService\x12+\n" +
	"\x11relationship_type\x18\x04 \x01(\tR\x10relationshipType\x12G\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2'.corkscrew.Relationship.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x11GetSchemasRequest\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"=\n" +
	"\x0eSchemaResponse\x12+\n" +
	"\aschemas\x18\x01 \x03(\v2\x11.corkscrew.SchemaR\aschemas\"\x89\x02\n" +
	"\x06Schema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x10\n" +
	"\x03sql\x18\x04 \x01(\tR\x03sql\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12;\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1f.corkscrew.Schema.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x02\n" +
	"\x10BatchScanRequest\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12%\n" +
	"\x0eresource_types\x18\x02 \x03(\tR\rresourceTypes\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12B\n" +
	"\afilters\x18\x04 \x03(\v2(.corkscrew.BatchScanRequest.FiltersEntryR\afilters\x123\n" +
	"\x15include_relationships\x18\x05 \x01(\bR\x14includeRelationships\x12 \n" +
	"\vconcurrency\x18\x06 \x01(\x05R\vconcurrency\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\x11BatchScanResponse\x121\n" +
	"\tresources\x18\x01 \x03(\v2\x13.corkscrew.ResourceR\tresources\x12*\n" +
	"\x05stats\x18\x02 \x01(\v2\x14.corkscrew.ScanStatsR\x05stats\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\xa4\x02\n" +
	"\x11StreamScanRequest\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12%\n" +
	"\x0eresource_types\x18\x02 \x03(\tR\rresourceTypes\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12C\n" +
	"\afilters\x18\x04 \x03(\v2).corkscrew.StreamScanRequest.FiltersEntryR\afilters\x123\n" +
	"\x15include_relationships\x18\x05 \x01(\bR\x14includeRelationships\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x03\n" +
	"\tScanStats\x12'\n" +
	"\x0ftotal_resources\x18\x01 \x01(\x05R\x0etotalResources\x12)\n" +
	"\x10failed_resources\x18\x02 \x01(\x05R\x0ffailedResources\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12Q\n" +
	"\x0fresource_counts\x18\x04 \x03(\v2(.corkscrew.ScanStats.ResourceCountsEntryR\x0eresourceCounts\x12N\n" +
	"\x0eservice_counts\x18\x05 \x03(\v2'.corkscrew.ScanStats.ServiceCountsEntryR\rserviceCounts\x1aA\n" +
	"\x13ResourceCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a@\n" +
	"\x12ServiceCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x87\x02\n" +
	"\vScanRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12=\n" +
	"\aoptions\x18\x02 \x03(\v2#.corkscrew.ScanRequest.OptionsEntryR\aoptions\x12%\n" +
	"\x0eresource_types\x18\x03 \x03(\tR\rresourceTypes\x12\x1d\n" +
	"\n" +
	"next_token\x18\x04 \x01(\tR\tnextToken\x12\x1f\n" +
	"\vmax_results\x18\x05 \x01(\x05R\n" +
	"maxResults\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\fScanResponse\x121\n" +
	"\tresources\x18\x01 \x03(\v2\x13.corkscrew.ResourceR\tresources\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.corkscrew.ScanResponse.MetadataEntryR\bmetadata\x12*\n" +
	"\x05stats\x18\x05 \x01(\v2\x14.corkscrew.ScanStatsR\x05stats\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x02\n" +
	"\x13ServiceInfoResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12/\n" +
	"\x13supported_resources\x18\x03 \x03(\tR\x12supportedResources\x121\n" +
	"\x14required_permissions\x18\x04 \x03(\tR\x13requiredPermissions\x12T\n" +
	"\fcapabilities\x18\x05 \x03(\v20.corkscrew.ServiceInfoResponse.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe4\x05\n" +
	"\rCloudProvider\x12I\n" +
	"\n" +
	"Initialize\x12\x1c.corkscrew.InitializeRequest\x1a\x1d.corkscrew.InitializeResponse\x12D\n" +
	"\x0fGetProviderInfo\x12\x10.corkscrew.Empty\x1a\x1f.corkscrew.ProviderInfoResponse\x12[\n" +
	"\x10DiscoverServices\x12\".corkscrew.DiscoverServicesRequest\x1a#.corkscrew.DiscoverServicesResponse\x12b\n" +
	"\x17GenerateServiceScanners\x12\".corkscrew.GenerateScannersRequest\x1a#.corkscrew.GenerateScannersResponse\x12R\n" +
	"\rListResources\x12\x1f.corkscrew.ListResourcesRequest\x1a .corkscrew.ListResourcesResponse\x12[\n" +
	"\x10DescribeResource\x12\".corkscrew.DescribeResourceRequest\x1a#.corkscrew.DescribeResourceResponse\x12E\n" +
	"\n" +
	"GetSchemas\x12\x1c.corkscrew.GetSchemasRequest\x1a\x19.corkscrew.SchemaResponse\x12F\n" +
	"\tBatchScan\x12\x1b.corkscrew.BatchScanRequest\x1a\x1c.corkscrew.BatchScanResponse\x12A\n" +
	"\n" +
	"StreamScan\x12\x1c.corkscrew.StreamScanRequest\x1a\x13.corkscrew.Resource0\x012\xfe\x01\n" +
	"\aScanner\x127\n" +
	"\x04Scan\x12\x16.corkscrew.ScanRequest\x1a\x17.corkscrew.ScanResponse\x129\n" +
	"\n" +
	"GetSchemas\x12\x10.corkscrew.Empty\x1a\x19.corkscrew.SchemaResponse\x12B\n" +
	"\x0eGetServiceInfo\x12\x10.corkscrew.Empty\x1a\x1e.corkscrew.ServiceInfoResponse\x12;\n" +
	"\n" +
	"StreamScan\x12\x16.corkscrew.ScanRequest\x1a\x13.corkscrew.Resource0\x01B,Z*github.com/jlgore/corkscrew/internal/protob\x06proto3"

var (
	file_scanner_proto_rawDescOnce sync.Once
	file_scanner_proto_rawDescData []byte
)

func file_scanner_proto_rawDescGZIP() []byte {
	file_scanner_proto_rawDescOnce.Do(func() {
		file_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)))
	})
	return file_scanner_proto_rawDescData
}

var file_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_scanner_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: corkscrew.Empty
	(*InitializeRequest)(nil),        // 1: corkscrew.InitializeRequest
	(*InitializeResponse)(nil),       // 2: corkscrew.InitializeResponse
	(*ProviderInfoResponse)(nil),     // 3: corkscrew.ProviderInfoResponse
	(*DiscoverServicesRequest)(nil),  // 4: corkscrew.DiscoverServicesRequest
	(*DiscoverServicesResponse)(nil), // 5: corkscrew.DiscoverServicesResponse
	(*ServiceInfo)(nil),              // 6: corkscrew.ServiceInfo
	(*ResourceType)(nil),             // 7: corkscrew.ResourceType
	(*ResourceRelationship)(nil),     // 8: corkscrew.ResourceRelationship
	(*GenerateScannersRequest)(nil),  // 9: corkscrew.GenerateScannersRequest
	(*GenerateScannersResponse)(nil), // 10: corkscrew.GenerateScannersResponse
	(*GeneratedScanner)(nil),         // 11: corkscrew.GeneratedScanner
	(*ListResourcesRequest)(nil),     // 12: corkscrew.ListResourcesRequest
	(*ListResourcesResponse)(nil),    // 13: corkscrew.ListResourcesResponse
	(*ResourceRef)(nil),              // 14: corkscrew.ResourceRef
	(*DescribeResourceRequest)(nil),  // 15: corkscrew.DescribeResourceRequest
	(*DescribeResourceResponse)(nil), // 16: corkscrew.DescribeResourceResponse
	(*Resource)(nil),                 // 17: corkscrew.Resource
	(*Relationship)(nil),             // 18: corkscrew.Relationship
	(*GetSchemasRequest)(nil),        // 19: corkscrew.GetSchemasRequest
	(*SchemaResponse)(nil),           // 20: corkscrew.SchemaResponse
	(*Schema)(nil),                   // 21: corkscrew.Schema
	(*BatchScanRequest)(nil),         // 22: corkscrew.BatchScanRequest
	(*BatchScanResponse)(nil),        // 23: corkscrew.BatchScanResponse
	(*StreamScanRequest)(nil),        // 24: corkscrew.StreamScanRequest
	(*ScanStats)(nil),                // 25: corkscrew.ScanStats
	(*ScanRequest)(nil),              // 26: corkscrew.ScanRequest
	(*ScanResponse)(nil),             // 27: corkscrew.ScanResponse
	(*ServiceInfoResponse)(nil),      // 28: corkscrew.ServiceInfoResponse
	nil,                              // 29: corkscrew.InitializeRequest.ConfigEntry
	nil,                              // 30: corkscrew.InitializeResponse.MetadataEntry
	nil,                              // 31: corkscrew.ProviderInfoResponse.CapabilitiesEntry
	nil,                              // 32: corkscrew.ListResourcesRequest.FiltersEntry
	nil,                              // 33: corkscrew.ListResourcesResponse.MetadataEntry
	nil,                              // 34: corkscrew.ResourceRef.BasicAttributesEntry
	nil,                              // 35: corkscrew.Resource.TagsEntry
	nil,                              // 36: corkscrew.Relationship.PropertiesEntry
	nil,                              // 37: corkscrew.Schema.MetadataEntry
	nil,                              // 38: corkscrew.BatchScanRequest.FiltersEntry
	nil,                              // 39: corkscrew.StreamScanRequest.FiltersEntry
	nil,                              // 40: corkscrew.ScanStats.ResourceCountsEntry
	nil,                              // 41: corkscrew.ScanStats.ServiceCountsEntry
	nil,                              // 42: corkscrew.ScanRequest.OptionsEntry
	nil,                              // 43: corkscrew.ScanResponse.MetadataEntry
	nil,                              // 44: corkscrew.ServiceInfoResponse.CapabilitiesEntry
	(*timestamppb.Timestamp)(nil),    // 45: google.protobuf.Timestamp
}
var file_scanner_proto_depIdxs = []int32{
	29, // 0: corkscrew.InitializeRequest.config:type_name -> corkscrew.InitializeRequest.ConfigEntry
	30, // 1: corkscrew.InitializeResponse.metadata:type_name -> corkscrew.InitializeResponse.MetadataEntry
	31, // 2: corkscrew.ProviderInfoResponse.capabilities:type_name -> corkscrew.ProviderInfoResponse.CapabilitiesEntry
	6,  // 3: corkscrew.DiscoverServicesResponse.services:type_name -> corkscrew.ServiceInfo
	45, // 4: corkscrew.DiscoverServicesResponse.discovered_at:type_name -> google.protobuf.Timestamp
	7,  // 5: corkscrew.ServiceInfo.resource_types:type_name -> corkscrew.ResourceType
	8,  // 6: corkscrew.ResourceType.relationships:type_name -> corkscrew.ResourceRelationship
	11, // 7: corkscrew.GenerateScannersResponse.scanners:type_name -> corkscrew.GeneratedScanner
	45, // 8: corkscrew.GeneratedScanner.generated_at:type_name -> google.protobuf.Timestamp
	32, // 9: corkscrew.ListResourcesRequest.filters:type_name -> corkscrew.ListResourcesRequest.FiltersEntry
	14, // 10: corkscrew.ListResourcesResponse.resources:type_name -> corkscrew.ResourceRef
	33, // 11: corkscrew.ListResourcesResponse.metadata:type_name -> corkscrew.ListResourcesResponse.MetadataEntry
	34, // 12: corkscrew.ResourceRef.basic_attributes:type_name -> corkscrew.ResourceRef.BasicAttributesEntry
	14, // 13: corkscrew.DescribeResourceRequest.resource_ref:type_name -> corkscrew.ResourceRef
	17, // 14: corkscrew.DescribeResourceResponse.resource:type_name -> corkscrew.Resource
	35, // 15: corkscrew.Resource.tags:type_name -> corkscrew.Resource.TagsEntry
	45, // 16: corkscrew.Resource.created_at:type_name -> google.protobuf.Timestamp
	45, // 17: corkscrew.Resource.modified_at:type_name -> google.protobuf.Timestamp
	45, // 18: corkscrew.Resource.discovered_at:type_name -> google.protobuf.Timestamp
	18, // 19: corkscrew.Resource.relationships:type_name -> corkscrew.Relationship
	36, // 20: corkscrew.Relationship.properties:type_name -> corkscrew.Relationship.PropertiesEntry
	21, // 21: corkscrew.SchemaResponse.schemas:type_name -> corkscrew.Schema
	37, // 22: corkscrew.Schema.metadata:type_name -> corkscrew.Schema.MetadataEntry
	38, // 23: corkscrew.BatchScanRequest.filters:type_name -> corkscrew.BatchScanRequest.FiltersEntry
	17, // 24: corkscrew.BatchScanResponse.resources:type_name -> corkscrew.Resource
	25, // 25: corkscrew.BatchScanResponse.stats:type_name -> corkscrew.ScanStats
	39, // 26: corkscrew.StreamScanRequest.filters:type_name -> corkscrew.StreamScanRequest.FiltersEntry
	40, // 27: corkscrew.ScanStats.resource_counts:type_name -> corkscrew.ScanStats.ResourceCountsEntry
	41, // 28: corkscrew.ScanStats.service_counts:type_name -> corkscrew.ScanStats.ServiceCountsEntry
	42, // 29: corkscrew.ScanRequest.options:type_name -> corkscrew.ScanRequest.OptionsEntry
	17, // 30: corkscrew.ScanResponse.resources:type_name -> corkscrew.Resource
	43, // 31: corkscrew.ScanResponse.metadata:type_name -> corkscrew.ScanResponse.MetadataEntry
	25, // 32: corkscrew.ScanResponse.stats:type_name -> corkscrew.ScanStats
	44, // 33: corkscrew.ServiceInfoResponse.capabilities:type_name -> corkscrew.ServiceInfoResponse.CapabilitiesEntry
	1,  // 34: corkscrew.CloudProvider.Initialize:input_type -> corkscrew.InitializeRequest
	0,  // 35: corkscrew.CloudProvider.GetProviderInfo:input_type -> corkscrew.Empty
	4,  // 36: corkscrew.CloudProvider.DiscoverServices:input_type -> corkscrew.DiscoverServicesRequest
	9,  // 37: corkscrew.CloudProvider.GenerateServiceScanners:input_type -> corkscrew.GenerateScannersRequest
	12, // 38: corkscrew.CloudProvider.ListResources:input_type -> corkscrew.ListResourcesRequest
	15, // 39: corkscrew.CloudProvider.DescribeResource:input_type -> corkscrew.DescribeResourceRequest
	19, // 40: corkscrew.CloudProvider.GetSchemas:input_type -> corkscrew.GetSchemasRequest
	22, // 41: corkscrew.CloudProvider.BatchScan:input_type -> corkscrew.BatchScanRequest
	24, // 42: corkscrew.CloudProvider.StreamScan:input_type -> corkscrew.StreamScanRequest
	26, // 43: corkscrew.Scanner.Scan:input_type -> corkscrew.ScanRequest
	0,  // 44: corkscrew.Scanner.GetSchemas:input_type -> corkscrew.Empty
	0,  // 45: corkscrew.Scanner.GetServiceInfo:input_type -> corkscrew.Empty
	26, // 46: corkscrew.Scanner.StreamScan:input_type -> corkscrew.ScanRequest
	2,  // 47: corkscrew.CloudProvider.Initialize:output_type -> corkscrew.InitializeResponse
	3,  // 48: corkscrew.CloudProvider.GetProviderInfo:output_type -> corkscrew.ProviderInfoResponse
	5,  // 49: corkscrew.CloudProvider.DiscoverServices:output_type -> corkscrew.DiscoverServicesResponse
	10, // 50: corkscrew.CloudProvider.GenerateServiceScanners:output_type -> corkscrew.GenerateScannersResponse
	13, // 51: corkscrew.CloudProvider.ListResources:output_type -> corkscrew.ListResourcesResponse
	16, // 52: corkscrew.CloudProvider.DescribeResource:output_type -> corkscrew.DescribeResourceResponse
	20, // 53: corkscrew.CloudProvider.GetSchemas:output_type -> corkscrew.SchemaResponse
	23, // 54: corkscrew.CloudProvider.BatchScan:output_type -> corkscrew.BatchScanResponse
	17, // 55: corkscrew.CloudProvider.StreamScan:output_type -> corkscrew.Resource
	27, // 56: corkscrew.Scanner.Scan:output_type -> corkscrew.ScanResponse
	20, // 57: corkscrew.Scanner.GetSchemas:output_type -> corkscrew.SchemaResponse
	28, // 58: corkscrew.Scanner.GetServiceInfo:output_type -> corkscrew.ServiceInfoResponse
	17, // 59: corkscrew.Scanner.StreamScan:output_type -> corkscrew.Resource
	47, // [47:60] is the sub-list for method output_type
	34, // [34:47] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_scanner_proto_init() }
func file_scanner_proto_init() {
	if File_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_scanner_proto_goTypes,
		DependencyIndexes: file_scanner_proto_depIdxs,
		MessageInfos:      file_scanner_proto_msgTypes,
	}.Build()
	File_scanner_proto = out.File
	file_scanner_proto_goTypes = nil
	file_scanner_proto_depIdxs = nil
}
