// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: scanner.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{0}
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceTypes []string               `protobuf:"bytes,3,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	// For pagination support
	NextToken     string `protobuf:"bytes,4,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	MaxResults    int32  `protobuf:"varint,5,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ScanRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ScanRequest) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *ScanRequest) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *ScanRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type Resource struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id        string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Arn       string                 `protobuf:"bytes,3,opt,name=arn,proto3" json:"arn,omitempty"`
	ParentId  string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Region    string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	AccountId string                 `protobuf:"bytes,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Raw AWS API response as JSON
	RawData string `protobuf:"bytes,7,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	// Extracted key fields for common queries
	Tags       map[string]string    `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name       string               `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt  *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt *timestamp.Timestamp `protobuf:"bytes,11,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	// For graph relationships
	Relationships []*Relationship `protobuf:"bytes,12,rep,name=relationships,proto3" json:"relationships,omitempty"`
	// Service-specific attributes as JSON
	Attributes    string `protobuf:"bytes,13,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

func (x *Resource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Resource) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Resource) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Resource) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *Resource) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resource) GetModifiedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *Resource) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *Resource) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

type Relationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetId         string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType       string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	RelationshipType string                 `protobuf:"bytes,3,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	Properties       map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *Relationship) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Relationship) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *Relationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *Relationship) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stats         *ScanStats             `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *ScanResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ScanResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *ScanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScanResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ScanResponse) GetStats() *ScanStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ScanStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalResources  int32                  `protobuf:"varint,1,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`
	FailedResources int32                  `protobuf:"varint,2,opt,name=failed_resources,json=failedResources,proto3" json:"failed_resources,omitempty"`
	DurationMs      int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ResourceCounts  map[string]int32       `protobuf:"bytes,4,rep,name=resource_counts,json=resourceCounts,proto3" json:"resource_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScanStats) Reset() {
	*x = ScanStats{}
	mi := &file_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanStats) ProtoMessage() {}

func (x *ScanStats) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanStats.ProtoReflect.Descriptor instead.
func (*ScanStats) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *ScanStats) GetTotalResources() int32 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *ScanStats) GetFailedResources() int32 {
	if x != nil {
		return x.FailedResources
	}
	return 0
}

func (x *ScanStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ScanStats) GetResourceCounts() map[string]int32 {
	if x != nil {
		return x.ResourceCounts
	}
	return nil
}

type SchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*Schema              `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaResponse) Reset() {
	*x = SchemaResponse{}
	mi := &file_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaResponse) ProtoMessage() {}

func (x *SchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaResponse.ProtoReflect.Descriptor instead.
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *SchemaResponse) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_scanner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{7}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *Schema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ServiceInfoResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceName         string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version             string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedResources  []string               `protobuf:"bytes,3,rep,name=supported_resources,json=supportedResources,proto3" json:"supported_resources,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,4,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	Capabilities        map[string]string      `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceInfoResponse) Reset() {
	*x = ServiceInfoResponse{}
	mi := &file_scanner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoResponse) ProtoMessage() {}

func (x *ServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*ServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceInfoResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfoResponse) GetSupportedResources() []string {
	if x != nil {
		return x.SupportedResources
	}
	return nil
}

func (x *ServiceInfoResponse) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

func (x *ServiceInfoResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_scanner_proto protoreflect.FileDescriptor

const file_scanner_proto_rawDesc = "" +
	"\n" +
	"\rscanner.proto\x12\tcorkscrew\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\x87\x02\n" +
	"\vScanRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12=\n" +
	"\aoptions\x18\x02 \x03(\v2#.corkscrew.ScanRequest.OptionsEntryR\aoptions\x12%\n" +
	"\x0eresource_types\x18\x03 \x03(\tR\rresourceTypes\x12\x1d\n" +
	"\n" +
	"next_token\x18\x04 \x01(\tR\tnextToken\x12\x1f\n" +
	"\vmax_results\x18\x05 \x01(\x05R\n" +
	"maxResults\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x04\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03arn\x18\x03 \x01(\tR\x03arn\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\tR\taccountId\x12\x19\n" +
	"\braw_data\x18\a \x01(\tR\arawData\x121\n" +
	"\x04tags\x18\b \x03(\v2\x1d.corkscrew.Resource.TagsEntryR\x04tags\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12=\n" +
	"\rrelationships\x18\f \x03(\v2\x17.corkscrew.RelationshipR\rrelationships\x12\x1e\n" +
	"\n" +
	"attributes\x18\r \x01(\tR\n" +
	"attributes\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\fRelationship\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12+\n" +
	"\x11relationship_type\x18\x03 \x01(\tR\x10relationshipType\x12G\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2'.corkscrew.Relationship.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\fScanResponse\x121\n" +
	"\tresources\x18\x01 \x03(\v2\x13.corkscrew.ResourceR\tresources\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.corkscrew.ScanResponse.MetadataEntryR\bmetadata\x12*\n" +
	"\x05stats\x18\x05 \x01(\v2\x14.corkscrew.ScanStatsR\x05stats\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x02\n" +
	"\tScanStats\x12'\n" +
	"\x0ftotal_resources\x18\x01 \x01(\x05R\x0etotalResources\x12)\n" +
	"\x10failed_resources\x18\x02 \x01(\x05R\x0ffailedResources\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12Q\n" +
	"\x0fresource_counts\x18\x04 \x03(\v2(.corkscrew.ScanStats.ResourceCountsEntryR\x0eresourceCounts\x1aA\n" +
	"\x13ResourceCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"=\n" +
	"\x0eSchemaResponse\x12+\n" +
	"\aschemas\x18\x01 \x03(\v2\x11.corkscrew.SchemaR\aschemas\"P\n" +
	"\x06Schema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xcd\x02\n" +
	"\x13ServiceInfoResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12/\n" +
	"\x13supported_resources\x18\x03 \x03(\tR\x12supportedResources\x121\n" +
	"\x14required_permissions\x18\x04 \x03(\tR\x13requiredPermissions\x12T\n" +
	"\fcapabilities\x18\x05 \x03(\v20.corkscrew.ServiceInfoResponse.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xfe\x01\n" +
	"\aScanner\x127\n" +
	"\x04Scan\x12\x16.corkscrew.ScanRequest\x1a\x17.corkscrew.ScanResponse\x129\n" +
	"\n" +
	"GetSchemas\x12\x10.corkscrew.Empty\x1a\x19.corkscrew.SchemaResponse\x12B\n" +
	"\x0eGetServiceInfo\x12\x10.corkscrew.Empty\x1a\x1e.corkscrew.ServiceInfoResponse\x12;\n" +
	"\n" +
	"StreamScan\x12\x16.corkscrew.ScanRequest\x1a\x13.corkscrew.Resource0\x01B6Z4github.com/jlgore/corkscrew-generator/internal/protob\x06proto3"

var (
	file_scanner_proto_rawDescOnce sync.Once
	file_scanner_proto_rawDescData []byte
)

func file_scanner_proto_rawDescGZIP() []byte {
	file_scanner_proto_rawDescOnce.Do(func() {
		file_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)))
	})
	return file_scanner_proto_rawDescData
}

var file_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_scanner_proto_goTypes = []any{
	(*Empty)(nil),               // 0: corkscrew.Empty
	(*ScanRequest)(nil),         // 1: corkscrew.ScanRequest
	(*Resource)(nil),            // 2: corkscrew.Resource
	(*Relationship)(nil),        // 3: corkscrew.Relationship
	(*ScanResponse)(nil),        // 4: corkscrew.ScanResponse
	(*ScanStats)(nil),           // 5: corkscrew.ScanStats
	(*SchemaResponse)(nil),      // 6: corkscrew.SchemaResponse
	(*Schema)(nil),              // 7: corkscrew.Schema
	(*ServiceInfoResponse)(nil), // 8: corkscrew.ServiceInfoResponse
	nil,                         // 9: corkscrew.ScanRequest.OptionsEntry
	nil,                         // 10: corkscrew.Resource.TagsEntry
	nil,                         // 11: corkscrew.Relationship.PropertiesEntry
	nil,                         // 12: corkscrew.ScanResponse.MetadataEntry
	nil,                         // 13: corkscrew.ScanStats.ResourceCountsEntry
	nil,                         // 14: corkscrew.ServiceInfoResponse.CapabilitiesEntry
	(*timestamp.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_scanner_proto_depIdxs = []int32{
	9,  // 0: corkscrew.ScanRequest.options:type_name -> corkscrew.ScanRequest.OptionsEntry
	10, // 1: corkscrew.Resource.tags:type_name -> corkscrew.Resource.TagsEntry
	15, // 2: corkscrew.Resource.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: corkscrew.Resource.modified_at:type_name -> google.protobuf.Timestamp
	3,  // 4: corkscrew.Resource.relationships:type_name -> corkscrew.Relationship
	11, // 5: corkscrew.Relationship.properties:type_name -> corkscrew.Relationship.PropertiesEntry
	2,  // 6: corkscrew.ScanResponse.resources:type_name -> corkscrew.Resource
	12, // 7: corkscrew.ScanResponse.metadata:type_name -> corkscrew.ScanResponse.MetadataEntry
	5,  // 8: corkscrew.ScanResponse.stats:type_name -> corkscrew.ScanStats
	13, // 9: corkscrew.ScanStats.resource_counts:type_name -> corkscrew.ScanStats.ResourceCountsEntry
	7,  // 10: corkscrew.SchemaResponse.schemas:type_name -> corkscrew.Schema
	14, // 11: corkscrew.ServiceInfoResponse.capabilities:type_name -> corkscrew.ServiceInfoResponse.CapabilitiesEntry
	1,  // 12: corkscrew.Scanner.Scan:input_type -> corkscrew.ScanRequest
	0,  // 13: corkscrew.Scanner.GetSchemas:input_type -> corkscrew.Empty
	0,  // 14: corkscrew.Scanner.GetServiceInfo:input_type -> corkscrew.Empty
	1,  // 15: corkscrew.Scanner.StreamScan:input_type -> corkscrew.ScanRequest
	4,  // 16: corkscrew.Scanner.Scan:output_type -> corkscrew.ScanResponse
	6,  // 17: corkscrew.Scanner.GetSchemas:output_type -> corkscrew.SchemaResponse
	8,  // 18: corkscrew.Scanner.GetServiceInfo:output_type -> corkscrew.ServiceInfoResponse
	2,  // 19: corkscrew.Scanner.StreamScan:output_type -> corkscrew.Resource
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_scanner_proto_init() }
func file_scanner_proto_init() {
	if File_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scanner_proto_goTypes,
		DependencyIndexes: file_scanner_proto_depIdxs,
		MessageInfos:      file_scanner_proto_msgTypes,
	}.Build()
	File_scanner_proto = out.File
	file_scanner_proto_goTypes = nil
	file_scanner_proto_depIdxs = nil
}
