project_name: corkscrew

# Build configuration
builds:
  # Main CLI binary
  - id: corkscrew-cli
    main: ./cmd/corkscrew
    binary: corkscrew
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # Plugins are built on-demand by users
  # No pre-built plugin binaries in releases

# Pre-build hooks
before:
  hooks:
    - make deps
    - make generate-proto
    - make fmt
    - make test-unit

# Archive configuration
archives:
  - id: cli
    builds:
      - corkscrew-cli
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - AWS_SCANNING_DOCUMENTATION.md
      - AZURE_SCANNING_DOCUMENTATION.md
      - plugins/
  
  # No separate plugin archives - plugins built on-demand from source

# Checksums
checksum:
  name_template: 'checksums.txt'

# Snapshots (for non-tag builds)
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch

# GitHub release
release:
  github:
    owner: '{{ .Env.GITHUB_REPOSITORY_OWNER }}'
    name: '{{ .Env.GITHUB_REPOSITORY }}'
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Corkscrew {{ .Tag }}
    
    Cloud Resource Scanner release with cross-platform CLI binary.
    
    ### Installation
    
    Download the appropriate binary for your platform:
    - **Linux**: `corkscrew_linux_amd64.tar.gz` or `corkscrew_linux_arm64.tar.gz`
    - **macOS**: `corkscrew_darwin_amd64.tar.gz` or `corkscrew_darwin_arm64.tar.gz` (Apple Silicon)
    - **Windows**: `corkscrew_windows_amd64.zip`
    
    ### Plugins
    
    Cloud provider plugins are built automatically when first used:
    ```bash
    # Plugins auto-build on first use
    corkscrew discover --provider aws    # Builds AWS plugin if needed
    corkscrew discover --provider azure  # Builds Azure plugin if needed
    corkscrew discover --provider gcp    # Builds GCP plugin if needed
    ```
    
    Or build manually:
    ```bash
    make build-aws-plugin     # Build AWS plugin
    make build-azure-plugin   # Build Azure plugin  
    make build-gcp-plugin     # Build GCP plugin
    ```
    
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

# Universal binaries for macOS
universal_binaries:
  - replace: true

# Homebrew formula (optional)
brews:
  - name: corkscrew
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
    description: "Cloud Resource Scanner - Discover and analyze cloud resources across multiple providers"
    license: "MIT"
    test: |
      system "#{bin}/corkscrew --version"
    install: |
      bin.install "corkscrew" 